
// Zivo Organization Token
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ0lkIjoxLCJpYXQiOjE3Njk5MTUyNzQsImV4cCI6MTc3MDAwMTY3NH0.hpVMGa0Y2_CwLNZybiTSVVyyWoEQcrD9fZXOS0trsRM

// OneAi Organization Token
# @token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm9yZ0lkIjoyLCJpYXQiOjE3Njk3NTE3MTcsImV4cCI6MTc2OTgzODExN30.Veg-X_jiV53fAYChRJWW0aN3ABtFlz7P8fJRKP7OEso
### Add new user and organization
POST http://localhost:5000/auth/register
Content-Type: application/json

 {
  "orgName": "Zivo",
  "adminName": "Yugandhar",
  "email": "boyayugandhar135@gmail.com",
  "password": "Yuga@123"
}

# {
#     "orgName": "OneAi",
#    "adminName": "Yugandhar",
#     "email": "boyayugandhar6@gmail.com",
#     "password": "Yuga@123"
# }


### get all users
GET http://localhost:5000/users  

### Login user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@evallo.com",
  "password": "admin123"
}

### Add new team 
POST http://localhost:5000/teams
Content-Type: application/json
Authorization: Bearer {{token}}

 {
    "name": "Operations Team",
    "description": "Oversees company operations and process efficiency"
  }
  

### get all teams
GET http://localhost:5000/teams
Authorization: Bearer {{token}}

### delete team by ID
DELETE http://localhost:5000/teams/4
Authorization: Bearer {{token}}

### Add new employee
POST http://localhost:5000/employees
Content-Type: application/json
Authorization: Bearer {{token}}

 {
  "firstName": "john",
  "lastName": "Smith",
  "email": "alice@example.com",
  "phone": "9876543210"
}

### Get all employees
GET http://localhost:5000/employees
Authorization: Bearer {{token}}

### Get employee by ID
GET http://localhost:5000/employees/1
Authorization: Bearer {{token}}

### Update employee by ID
PUT http://localhost:5000/employees/1
Content-Type: application/json
Authorization: Bearer {{token}}

 {
  "firstName": "Alice",
  "lastName": "Johnson",
  "email": "alice.johnson@example.com",
  "phone": "9123456780"
}
### Delete employee by ID
DELETE http://localhost:5000/employees/6
Authorization: Bearer {{token}}

### Add new team
POST http://localhost:5000/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Frontend Team",
  "description": "Handles UI development and React projects"
}

### Get all teams
GET http://localhost:5000/teams 
Authorization: Bearer {{token}}
### Get team by ID
GET http://localhost:5000/teams/1
Authorization: Bearer {{token}}

### Update team by ID
PUT http://localhost:5000/teams/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Backend Team",
  "description": "Handles server-side development and database management"
}
### Delete team by ID
DELETE http://localhost:5000/teams/1
Authorization: Bearer {{token}}

### Assign employee to a team
POST http://localhost:5000/teams/2/assign_team
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "employeeId":6
}

### Unassign employee from a team
POST http://localhost:5000/teams/2/unassign
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "employeeId": 3
}

### Get all employees in a team
GET http://localhost:5000/teams/2/members
Authorization: Bearer {{token}}

### Get all assigned members of organization
GET http://localhost:5000/assigned_members
Authorization: Bearer {{token}}
